package studio

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// ExportEmbeddedGo emits the spec's studio-owned source mode artifact: a
// deterministic generated Go file that embeds the canonical `.scene3d`
// document and exposes stable-ID constants so applications bind runtime
// behavior by identity instead of by name. The canonical bytes are embedded
// verbatim, so the export is lossless.
func ExportEmbeddedGo(document Document, packageName string) ([]byte, ExportReport, error) {
	if !validGoIdentifier(packageName) {
		return nil, ExportReport{}, fmt.Errorf("package name %q is not a valid Go identifier", packageName)
	}
	payload, docReport, err := ExportSceneDoc(document)
	if err != nil {
		return nil, ExportReport{}, err
	}
	var out strings.Builder
	out.WriteString("// Code generated by GoSX 3D Studio (" + SceneDocSchema + "). DO NOT EDIT.\n")
	out.WriteString("//\n// The embedded document is the authoring source of truth; edit it in\n")
	out.WriteString("// GoSX 3D Studio and regenerate this file. Bind runtime behavior through\n")
	out.WriteString("// the stable-ID constants below, never through display names.\n")
	out.WriteString("package " + packageName + "\n\n")
	out.WriteString("// DocumentFingerprint identifies the exact embedded document revision.\n")
	out.WriteString("const DocumentFingerprint = " + strconv.Quote(docReport.Fingerprint) + "\n\n")
	out.WriteString(fmt.Sprintf("// DocumentRevision mirrors the document's revision counter.\nconst DocumentRevision = %d\n\n", document.Revision))
	out.WriteString("// DocumentJSON is the canonical .scene3d payload.\n")
	out.WriteString("const DocumentJSON = " + strconv.Quote(string(payload)) + "\n\n")

	writeConstants := func(comment, prefix string, ids []string) {
		if len(ids) == 0 {
			return
		}
		sort.Strings(ids)
		out.WriteString("// " + comment + "\nconst (\n")
		used := map[string]bool{}
		for _, id := range ids {
			name := prefix + goIdentifierFragment(id)
			for used[name] {
				name += "X"
			}
			used[name] = true
			out.WriteString("\t" + name + " = " + strconv.Quote(id) + "\n")
		}
		out.WriteString(")\n\n")
	}
	entityIDs := make([]string, 0, len(document.Entities))
	for id := range document.Entities {
		entityIDs = append(entityIDs, string(id))
	}
	writeConstants("Stable entity IDs.", "Entity", entityIDs)
	materialIDs := make([]string, 0, len(document.Materials))
	for id := range document.Materials {
		materialIDs = append(materialIDs, string(id))
	}
	writeConstants("Stable material IDs.", "Material", materialIDs)

	generated := []byte(out.String())
	return generated, exportReport("go-embed", "gosx.scene3d.go-embed/v1", document, generated, nil), nil
}

func validGoIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if !unicode.IsLetter(r) && r != '_' && (index == 0 || !unicode.IsDigit(r)) {
			return false
		}
	}
	return true
}

// goIdentifierFragment converts a stable ID into a deterministic exported
// identifier fragment: split on non-alphanumerics, capitalize each part.
func goIdentifierFragment(id string) string {
	var out strings.Builder
	capitalize := true
	for _, r := range id {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			capitalize = true
			continue
		}
		if capitalize {
			out.WriteRune(unicode.ToUpper(r))
			capitalize = false
			continue
		}
		out.WriteRune(r)
	}
	if out.Len() == 0 {
		return "Unnamed"
	}
	return out.String()
}
